# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'studentdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StudentDialog(object):
    def setupUi(self, StudentDialog):
        StudentDialog.setObjectName("StudentDialog")
        StudentDialog.resize(548, 584)
        StudentDialog.setStyleSheet("QDialog{\n"
"    background-color: white;\n"
"}\n"
"QLineEdit{    \n"
"    border: 1px solid gray;\n"
"    border-radius: 6px;\n"
"    padding-left: 15px;\n"
"    height: 35px;\n"
"}\n"
"QDateEdit{\n"
"    border: 1px solid gray;\n"
"    border-radius: 6px;\n"
"    padding-left: 15px;\n"
"    height: 31px;\n"
"}\n"
"QComboBox{\n"
"    border: 2px solid white;\n"
"    border-radius: 8px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    background-color: black;\n"
"    color: white;\n"
"    height: 35px;\n"
"    padding-left: 15px;\n"
"    font-weight: bold;\n"
"    selection-background-color:#5ce9ff;\n"
"}")
        self.line = QtWidgets.QFrame(StudentDialog)
        self.line.setGeometry(QtCore.QRect(-30, 60, 591, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(StudentDialog)
        self.label.setGeometry(QtCore.QRect(10, 20, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(StudentDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 70, 511, 441))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.name_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.name_lineEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.name_lineEdit.setMaximumSize(QtCore.QSize(16777215, 35))
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.verticalLayout.addWidget(self.name_lineEdit)
        self.verticalLayout_8.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.gender_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.gender_comboBox.setObjectName("gender_comboBox")
        self.gender_comboBox.addItem("")
        self.gender_comboBox.addItem("")
        self.gender_comboBox.addItem("")
        self.gender_comboBox.addItem("")
        self.verticalLayout_5.addWidget(self.gender_comboBox)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.class_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.class_comboBox.setObjectName("class_comboBox")
        self.class_comboBox.addItem("")
        self.class_comboBox.addItem("")
        self.class_comboBox.addItem("")
        self.class_comboBox.addItem("")
        self.class_comboBox.addItem("")
        self.verticalLayout_6.addWidget(self.class_comboBox)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.dob_dateEdit = QtWidgets.QDateEdit(self.layoutWidget)
        self.dob_dateEdit.setObjectName("dob_dateEdit")
        self.verticalLayout_7.addWidget(self.dob_dateEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.department_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.department_comboBox.setMinimumSize(QtCore.QSize(0, 35))
        self.department_comboBox.setMaximumSize(QtCore.QSize(16777215, 35))
        self.department_comboBox.setObjectName("department_comboBox")
        self.department_comboBox.addItem("")
        self.department_comboBox.addItem("")
        self.department_comboBox.addItem("")
        self.department_comboBox.addItem("")
        self.department_comboBox.addItem("")
        self.department_comboBox.addItem("")
        self.verticalLayout_3.addWidget(self.department_comboBox)
        self.verticalLayout_8.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.phone_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.phone_lineEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.phone_lineEdit.setMaximumSize(QtCore.QSize(16777215, 35))
        self.phone_lineEdit.setObjectName("phone_lineEdit")
        self.verticalLayout_4.addWidget(self.phone_lineEdit)
        self.verticalLayout_8.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.email_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.email_lineEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.email_lineEdit.setMaximumSize(QtCore.QSize(16777215, 35))
        self.email_lineEdit.setObjectName("email_lineEdit")
        self.verticalLayout_2.addWidget(self.email_lineEdit)
        self.verticalLayout_8.addLayout(self.verticalLayout_2)
        self.layoutWidget1 = QtWidgets.QWidget(StudentDialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 520, 511, 45))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.saveStudent_btn_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.saveStudent_btn_2.setMinimumSize(QtCore.QSize(100, 41))
        self.saveStudent_btn_2.setMaximumSize(QtCore.QSize(100, 41))
        self.saveStudent_btn_2.setStyleSheet("QPushButton{\n"
"    background-color: #ff3030;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"}")
        self.saveStudent_btn_2.setObjectName("saveStudent_btn_2")
        self.horizontalLayout_4.addWidget(self.saveStudent_btn_2)
        spacerItem = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.saveStudent_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.saveStudent_btn.setMinimumSize(QtCore.QSize(100, 41))
        self.saveStudent_btn.setMaximumSize(QtCore.QSize(100, 41))
        self.saveStudent_btn.setStyleSheet("QPushButton{\n"
"    background-color: #5ce9ff;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px\n"
"}")
        self.saveStudent_btn.setObjectName("saveStudent_btn")
        self.horizontalLayout_3.addWidget(self.saveStudent_btn)
        self.cancel_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.cancel_btn.setMinimumSize(QtCore.QSize(100, 41))
        self.cancel_btn.setMaximumSize(QtCore.QSize(100, 41))
        self.cancel_btn.setStyleSheet("QPushButton{\n"
"    background-color: #585858;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px\n"
"}")
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_3.addWidget(self.cancel_btn)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)

        self.retranslateUi(StudentDialog)
        QtCore.QMetaObject.connectSlotsByName(StudentDialog)

    def retranslateUi(self, StudentDialog):
        _translate = QtCore.QCoreApplication.translate
        StudentDialog.setWindowTitle(_translate("StudentDialog", "Dialog"))
        self.label.setText(_translate("StudentDialog", "Add New Student"))
        self.label_2.setText(_translate("StudentDialog", "Full Name"))
        self.label_6.setText(_translate("StudentDialog", "Select Gender"))
        self.gender_comboBox.setItemText(0, _translate("StudentDialog", "Gender"))
        self.gender_comboBox.setItemText(1, _translate("StudentDialog", "Male"))
        self.gender_comboBox.setItemText(2, _translate("StudentDialog", "Female"))
        self.gender_comboBox.setItemText(3, _translate("StudentDialog", "Other"))
        self.label_7.setText(_translate("StudentDialog", "Select Class"))
        self.class_comboBox.setItemText(0, _translate("StudentDialog", "Grade"))
        self.class_comboBox.setItemText(1, _translate("StudentDialog", "Level 100"))
        self.class_comboBox.setItemText(2, _translate("StudentDialog", "Level 200"))
        self.class_comboBox.setItemText(3, _translate("StudentDialog", "Level 300"))
        self.class_comboBox.setItemText(4, _translate("StudentDialog", "Level 400"))
        self.label_8.setText(_translate("StudentDialog", "Date of Birth"))
        self.label_4.setText(_translate("StudentDialog", "Department"))
        self.department_comboBox.setItemText(0, _translate("StudentDialog", "Select Department"))
        self.department_comboBox.setItemText(1, _translate("StudentDialog", "Computer Engineering"))
        self.department_comboBox.setItemText(2, _translate("StudentDialog", "Biomedical Engineering"))
        self.department_comboBox.setItemText(3, _translate("StudentDialog", "Materials Engineering"))
        self.department_comboBox.setItemText(4, _translate("StudentDialog", "Argricultural Engineering"))
        self.department_comboBox.setItemText(5, _translate("StudentDialog", "Food Processing Engineering"))
        self.label_5.setText(_translate("StudentDialog", "Student ID"))
        self.label_3.setText(_translate("StudentDialog", "Phone Number"))
        self.saveStudent_btn_2.setText(_translate("StudentDialog", "Fingerprint"))
        self.saveStudent_btn.setText(_translate("StudentDialog", "Add Student"))
        self.cancel_btn.setText(_translate("StudentDialog", "Cancel"))
